"""add retrieval_logs table for layer1 audit trail

Revision ID: 0013_retrieval_logs_table
Revises: 0012_campaign_pipeline_tracking
Create Date: 2026-07-02 12:20:11.495810
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '0013_retrieval_logs_table'
down_revision = '0012_campaign_pipeline_tracking'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retrieval_logs',
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('isolation_status', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('chunks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('brand_space_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_space_id'], ['brand_spaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrieval_logs_brand_space_id'), 'retrieval_logs', ['brand_space_id'], unique=False)
    op.create_index(op.f('ix_retrieval_logs_isolation_status'), 'retrieval_logs', ['isolation_status'], unique=False)
    op.create_index(op.f('ix_retrieval_logs_namespace'), 'retrieval_logs', ['namespace'], unique=False)
    op.create_index(op.f('ix_retrieval_logs_tenant_id'), 'retrieval_logs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retrieval_logs_tenant_id'), table_name='retrieval_logs')
    op.drop_index(op.f('ix_retrieval_logs_namespace'), table_name='retrieval_logs')
    op.drop_index(op.f('ix_retrieval_logs_isolation_status'), table_name='retrieval_logs')
    op.drop_index(op.f('ix_retrieval_logs_brand_space_id'), table_name='retrieval_logs')
    op.drop_table('retrieval_logs')
    # ### end Alembic commands ###

